# Generated by Django 3.0.3 on 2020-09-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default=None)),
                ('Occupation', models.TextField(default=None)),
                ('Age', models.IntegerField()),
                ('Username', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=120)),
            ],
        ),
    ]
