# Generated by Django 3.0.3 on 2020-09-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesignApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='Age',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='Password',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='Name',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Occupation',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Username',
        ),
    ]
