# Generated by Django 3.0.3 on 2020-09-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignApp', '0002_auto_20200906_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Height', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Description', models.CharField(max_length=120)),
            ],
        ),
    ]
